Orthogonal Vectors

In [1]:
import numpy as np

In [28]:
i = np.array([1, 0])
i

array([1, 0])

In [29]:
j = np.array([0, 1])
j

array([0, 1])

In [30]:
np.dot(i, j) # detail on the dot operation coming up...

np.int64(0)

In [31]:
# Bukti Orthogonal: Hitung Dot Product antara i dan j
# Rumus: (1*0) + (0*1) = 0
dot_product = np.dot(i, j)

print("Dot Product i dan j:", dot_product)

Dot Product i dan j: 0


In [10]:
if dot_product == 0:
    print("Kesimpulan: Vektor i dan j adalah Orthogonal.")
else:
    print("Kesimpulan: Vektor i dan j tidak Orthogonal.")

Kesimpulan: Vektor i dan j adalah Orthogonal.


Orthogonal Vectors

In [11]:
import numpy as np

In [20]:
# Membuat vektor v
v = np.array([1, 2])
v

array([1, 2])

In [21]:
# Membuat vektor w
w = np.array([2, -1])
w


array([ 2, -1])

In [27]:
# Bukti Orthogonal: Hitung Dot Product antara v dan w
# Rumus: (1*2) + (-2*1) = 0
dot_product = np.dot(v, w)

print("Dot Product v dan w:", dot_product)


Dot Product v dan w: 0


In [26]:
if dot_product == 0:
    print("Kesimpulan: Vektor i dan j adalah Orthogonal.")
else:
    print("Kesimpulan: Vektor i dan j tidak Orthogonal.")

Kesimpulan: Vektor i dan j adalah Orthogonal.
