Matrices (Rank 2 Tensors) in NumPy

In [9]:
import numpy as np

In [40]:
# Membuat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[6,8,2],[7,3,9]])
x

array([[6, 8, 2],
       [7, 3, 9]])

In [41]:
# Menampilkan ukuran matriks x
x.shape

(2, 3)

In [42]:
# Menampilkan jumlah elemen x
x.size

6

In [43]:
#  Menampilkan seluruh elemen dari kolom pertama matriks x
x[:, 0]

array([6, 7])

In [22]:
#  Menampilkan seluruh elemen dari baris kedua matriks x
x[1, :]

array([7, 3, 9])

Matrices in PyTorch

In [23]:
import torch

In [32]:
# Membuat matrix X berukuran 2x3 menggunakan torch
x_pt = torch.tensor([[6,8,2],[7,3,9]])
x_pt

tensor([[6, 8, 2],
        [7, 3, 9]])

In [25]:
# Menampilkan ukuran matriks x
x_pt.shape

torch.Size([2, 3])

In [26]:
# Menampilkan jumlah elemen x
x_pt.size

<function Tensor.size>

In [45]:
#  Menampilkan seluruh elemen dari kolom pertama matriks x dengan PyTorch
x_pt[:, 0]

tensor([6, 7])

In [44]:
#  Menampilkan seluruh elemen dari baris kedua matriks x dengan Pytorch
x_pt[1, :]

tensor([7, 3, 9])

Matrices in TensorFlow

In [30]:
import tensorflow as tf

In [34]:
# Membuat matriks X berukuran 2x3 dengan TensorFlow
x_tf = tf.Variable([[6,8,2],[7,3,9]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[6, 8, 2],
       [7, 3, 9]], dtype=int32)>

In [35]:
# Menampilkan ukuran matriks x
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [36]:
# Menampilkan jumlah elemen x
tf.size(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [38]:
#  Menampilkan seluruh elemen dari kolom pertama matriks x dengan tensorflow
x_tf[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 7], dtype=int32)>

In [39]:
#  Menampilkan seluruh elemen dari baris kedua matriks x dengan tensorflow
x_tf[1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 3, 9], dtype=int32)>