Vector

In [3]:
import numpy as np

In [75]:
# Membuat array NumPy (Vektor) Argumen tipe data bersifat opsional, contoh: dtype=np.float16
x = np.array([20, 4, 6])
x


array([20,  4,  6])

In [76]:
# Hitung panjang vector x
print(len(x))

3


In [77]:
# Tampilkan ukuran vector x
print("Ukuran vector x:", x.shape)

Ukuran vector x: (3,)


In [78]:
# Tampilkan tipe data dari vector x
print("Tipe data vector x:", type(x))

Tipe data vector x: <class 'numpy.ndarray'>


In [79]:
# Akses elemen pertama dari vector x
print("Elemen pertama:", x[0])

Elemen pertama: 20


In [43]:
# Tampilkan tipe data elemen pertama dari vector x
print("Tipe data elemen pertama:", type(x[0]))

Tipe data elemen pertama: <class 'numpy.int64'>


Vector Transposition

In [80]:
# Buat vector baris x (ukuran 1x3) agar bisa ditranspose menjadi 3x1
x_t = x.T
x_t

array([20,  4,  6])

In [45]:
# Tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [46]:
# Buat vector y (ukuran 1x3)
y = np.array([[13, 10, 25]])
y

array([[13, 10, 25]])

In [47]:
# Tampilkan ukuran dari vector x_t
y.shape

(1, 3)

In [48]:
# kita bisa melakukan transpose pada matriks yang salah satu dimensinya bernilai 1, yang secara matematis setara:
y_t = y.T
y_t

array([[13],
       [10],
       [25]])

In [50]:
y_t.shape # # ini adalah vektor kolom karena memiliki 3 baris dan 1 kolom

(3, 1)

In [51]:
# Vektor kolom dapat di-transpose kembali menjadi vektor baris aslinya:
y_t.T

array([[13, 10, 25]])

In [52]:
y_t.T.shape

(1, 3)

vector dengan pytorch

In [53]:
import torch

In [55]:
# Buat tensor 2D (1x3)
x_pt = torch.tensor([[20, 4, 6]])
x_pt

tensor([[20,  4,  6]])

In [56]:
x_pt.shape

torch.Size([1, 3])

vector dengan tensorflow

In [59]:
import tensorflow as tf

In [68]:
# # lakukan pada tahapan ini dengan tensorflow
#Buat variabel(1x3)
x_tf = tf.Variable([[20, 4, 6]])
x_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[20,  4,  6]], dtype=int32)>

In [66]:
y_tf2 = tf.Variable([[20, 4, 6]])
y_tf2

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[20,  4,  6]], dtype=int32)>

In [67]:
x_tf.shape

TensorShape([1, 3])

In [69]:
y_tf = tf.Variable([[20, 4, 6]])
print(f"variabel tensor y adalah :", y_tf)

variabel tensor y adalah : <tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[20,  4,  6]], dtype=int32)>


In [70]:
x_tf + y_tf

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[40,  8, 12]], dtype=int32)>

In [71]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[40,  8, 12]], dtype=int32)>

In [83]:
tf_sum.numpy() # perhatikan bahwa operasi NumPy secara otomatis mengubah tensor menjadi array NumPy, dan sebaliknya

array([[40,  8, 12]], dtype=int32)

In [82]:
type(tf_sum.numpy())

numpy.ndarray

In [81]:
tf_float = tf.Variable([[20, 4, 6]])
tf_float

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[20,  4,  6]], dtype=int32)>